name: Build App
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
    defaults:
      run:
        working-directory: ./echo
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: Install modules and build frontend
      run: |
        npm install
        cd ..
        cd electron
        mkdir build
        cd ..
        cd echo
        npm run build
    - name: Build app
      run: |
        cd ..
        cd electron
        npm install
        npm run make
    - name: Upload compiled folder
      uses: actions/upload-artifact@v3
      with:
        name: echo
        path: out/Echo-win32-x64
    - name: Upload compiled exes
      uses: actions/upload-artifact@v3
      with:
        name: echo
        path: out/make/squirrel.windows/x64

  create_tag:
    runs-on: ubuntu-latest
    needs: build
    # retreive last version tag
    # env:
    #   LAST_VERSION_TAG: $(git describe --abbrev=0 --tags)
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: Create tag
        # run the command to create the tag
      run: |
        git tag -a v${{ github.run_number }} -m "Release v${{ github.run_number }}"
        git push origin v${{ github.run_number }}

  release:
    runs-on: ubuntu-latest
    needs: create_tag
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: out/
        tag_name: ${{ github.ref }}
        body: |
          **Changes**
          ${{ github.event.release.body }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

  # build_on_linux:
  #   runs-on: ubuntu-latest
  #   needs: build_frontend
  #   defaults:
  #     run:
  #       working-directory: ./electron
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@master
  #     with:
  #       node-version: 18
  #   - name: Install modules and build
  #     run: |
  #       npm install
  #       npm run make

  # build_on_mac:
  #   runs-on: macos-latest
  #   needs: build_frontend
  #   defaults:
  #     run:
  #       working-directory: ./electron
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@master
  #     with:
  #       node-version: 18
  #   - name: Install modules and build
  #     run: |
  #       npm install
  #       npm run make

  # build_on_win:
  #   runs-on: windows-latest
  #   needs: build_frontend
  #   defaults:
  #     run:
  #       working-directory: ./electron
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@master
  #     with:
  #       node-version: 18
  #   - name: Install modules and build
  #     run: |
  #       npm install
  #       npm run make