name: Build and Release Electron App

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      CI: false
      GITHUB_TOKEN: ${{ secrets.zth_token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies for the React frontend
        working-directory: ./echo
        run: npm install

      - name: Build React Frontend
        working-directory: ./echo
        run: npm run build

      - name: Install dependencies for the Electron app
        working-directory: ./electron
        run: npm install

      - name: Build Electron App
        working-directory: ./electron
        run: npm run make

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0 # Replace with your desired version number
          release_name: Release v1.0.0 # Replace with your desired release name
          draft: false
          prerelease: false

      - name: Upload Electron App
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./electron/out/* # Change to the path where the Electron app build artifacts are located
          asset_name: electron-app.zip # Change to your desired asset name
          asset_content_type: application/zip
