name: Build Electron
on: [push, pull_request]

jobs:
  build_frontend:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./echo
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install dependencies
      run: npm install
    - name: build
      run: CI=false npm run build


  build_on_linux:
    runs-on: ubuntu-latest
    needs: build_frontend
    defaults:
      run:
        working-directory: ./electron
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run make

  build_on_mac:
    runs-on: macos-latest
    needs: build_frontend
    defaults:
      run:
        working-directory: ./electron
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run make

  build_on_win:
    runs-on: windows-latest
    needs: build_frontend
    defaults:
      run:
        working-directory: ./electron
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run make