name: Build App
on:
  pull_request:
    branches:
      - 'main'

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    env:
      CI: false
    defaults:
      run:
        working-directory: ./echo
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: Install modules and build
      run: |
        npm install
        npm run build

  build_on_linux:
    runs-on: ubuntu-latest
    needs: build_frontend
    defaults:
      run:
        working-directory: ./electron
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: Install modules and build
      run: |
        npm install
        npm run make

  build_on_mac:
    runs-on: macos-latest
    needs: build_frontend
    defaults:
      run:
        working-directory: ./electron
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: Install modules and build
      run: |
        npm install
        npm run make

  build_on_win:
    runs-on: windows-latest
    needs: build_frontend
    defaults:
      run:
        working-directory: ./electron
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: Install modules and build
      run: |
        npm install
        npm run make