name: Build and Release for Windows

on:
  push:
    branches:
      - main
      - dev
      - test_workflow

permissions:
  contents: write

jobs:
  build-and-release-windows:
    runs-on: windows-latest

    if: contains(github.event.head_commit.message, 'Create new release')

    env:
      CI: false
      GITHUB_TOKEN: ${{ secrets.zth_token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  update-readme:
    runs-on: ubuntu-latest
    needs: build-and-release-windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Update README
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.zth_token }}
          script: |
            const fs = require('fs');
            const readme = fs.readFileSync('README.md', 'utf-8');
            const newReadme = readme.replace(/v\d+\.\d+\.\d+/g, `v${{ steps.build-and-release-windows.outputs.release_echo_version }}`);
            fs.writeFileSync('README.md', newReadme);
            console.log('README updated');

      - name: Commit changes
        run: |
          git config --global user.name 'Automatic update'
          git config --global user.email 'actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.zth_token }}@github.com/${{ github.repository }}
          git commit -am "Updated version of readme"
          git push
