name: Build and Release Electron App

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      CI: false
      GITHUB_TOKEN: ${{ secrets.zth_token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies for the React frontend
        working-directory: ./echo
        run: npm install

      - name: Build React Frontend
        working-directory: ./echo
        run: npm run build

      - name: Install dependencies for the Electron app
        working-directory: ./electron
        run: npm install

      - name: Build Electron App
        working-directory: ./electron
        run: npm run make

      - name: Extract version from package.json
        id: extract_version
        run: echo "::set-output name=version::$(cat ./echo/package.json | jq -r .version)"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
          release_name: Release v${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Executables
        id: upload-executables
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.zth_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            ./electron/out/make/squirrel.windows/x64/Echo-0.1.0 Setup.exe 
          asset_name: echo-${{ steps.extract_version.outputs.version }}-executables.zip
          asset_content_type: application/zip

      - name: Upload Package
        id: upload-package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.zth_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            ./electron/out/make/squirrel.windows/x64/echo-0.1.0-full.nupkg
          asset_name: echo-${{ steps.extract_version.outputs.version }}.nupkg
          asset_content_type: application/zip

      - name: Upload Source Code
        id: upload-source-code
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.zth_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./electron/out/Echo-win32-x64
          asset_name: pre-compiled-${{ steps.extract_version.outputs.version }}.zip
          asset_content_type: application/zip