name: Release App

on:
  artifacts:
    paths:
      - 'out/**'
    name: echo
    types: [created]

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: Create tag
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git tag -a v${{ github.run_number }} -m "Release v${{ github.run_number }}"
        git push origin v${{ github.run_number }}
  release:
    runs-on: ubuntu-latest
    needs: create_tag
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: out/*
        tag_name: ${{ github.ref }}
        body: |
          **Changes**
          ${{ github.event.release.body }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
