name: Build and Release for Windows

on:
  push:
    branches:
      - main
      - dev
      - workflow

jobs:
  build-and-release-windows:
    runs-on: windows-latest

    if: contains(github.event.head_commit.message, 'Create new release test')

    env:
      CI: false
      GITHUB_TOKEN: ${{ secrets.zth_token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  update-readme:
    runs-on: ubuntu-latest
    needs: build-and-release-windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update README
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.zth_token }}
          script: |
            const fs = require('fs');
            const readme = fs.readFileSync('README.md', 'utf-8');
            const newReadme = readme.replace(/v\d+\.\d+\.\d+/g, `v${{ steps.build-and-release-windows.outputs.release_echo_version }}`);
            fs.writeFileSync('README.md', newReadme);
            console.log('README updated');

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update README.md"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.zth_token }}
